server:
  port: 21000
  contextPath: /termostato
  ip: localhost

spring:
  application.name: ST_Termostato_Uno

api.key: 32f4c32ae92647cab6400d58caa1b99c

device:
  id: ST_Termostato_Uno
  rest:
    local:
      schema: http
      network:
        interface: eth0
        ipv6: false
    basepath: /termostato
  register.fail.retry.seconds: 60
  ping.interval.seconds: 10
  logic.main.loop.delay.seconds: 30

onesaitplatform.digitaltwin.broker.rest: https://lab.onesaitplatform.com/digitaltwinbroker/
