server:
   port: 21001
   contextPath: /DetectorHumo
   ip: localhost

spring:
   application.name: ST_DetectorHumo_Uno

api.key: 017587dc53124f3a8a0d3b16c57ee9e0

device:
   id: ST_DetectorHumo_Uno
   rest:
     local:
        schema: http
        network:
           interface: eth0
           ipv6: false
     basepath: /DetectorHumo
   register.fail.retry.seconds: 60
   ping.interval.seconds: 10
   logic.main.loop.delay.seconds: 30
   broker:
      rest:
         enable: true
         swaggerhost: http://localhost:21001/DetectorHumo

onesaitplatform.digitaltwin.broker.rest: https://lab.onesaitplatform.com/digitaltwinbroker/
